# Generated by Django 5.1.1 on 2024-09-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
