# Generated by Django 5.1.1 on 2024-09-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
