# Generated by Django 5.1.1 on 2024-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(default="hi"),
            preserve_default=False,
        ),
    ]
