# Generated by Django 5.1.1 on 2024-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_comment_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
